import './style.css'
// import './class-and-inheritance'
// import './modules'
// import './optional-chaining'
// import './maps-&-sets'
// import './weakmap&weakset'
// import './symbol'
// import './simple-game'
// import './app'
// import './parse-API-response'
// import './graph'
// import './memoize'
// import './symbol-iterator'
import './event-emitter'